Files:
  prefix: File
  number: 6000
  filegroups:
    number: 500
    lenght: 5
    random: true
    p: 0.95

Modules:
  prefix: Module
  number: 200
  lambda: 50
  random: true

Authors:
  prefix: Author
  number: 10
  contribution: random

Issues:
  prefix: issue
  number: 500
  n_modules: 2
  lambda: 5
  random: true