Files:
  prefix: File
  number: 4000
  filegroups:
    number: 500
    lenght: 7
    random: true
    p: 0.93

Modules:
  prefix: Module
  number: 50
  lambda: 12
  random: true

Authors:
  prefix: Author
  number: 6
  contribution: random

Issues:
  prefix: issue
  number: 150
  n_modules: 2
  lambda: 10
  random: true